apiVersion: v1
kind: ServiceAccount
metadata:
  name: manuela-visual-inspection-ui
  namespace: manuela-visual-inspection-ui
  labels:
    app.kubernetes.io/instance: manuela-visual-inspection-ui
    app.kubernetes.io/name: manuela-visual-inspection-ui
